using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace Accounting_System.Models
{
    public partial class TXntc
    {
        public decimal PkId { get; set; }
        public int? FkChungtu { get; set; }
        public string CSophieu { get; set; }
        public byte FkDvcs { get; set; }
        public byte? FkTruso { get; set; }
        public DateTime? CNgaylap { get; set; }
        public DateTime? CNgayct { get; set; }
        public string CSoct { get; set; }
        public int? FkKhachhang { get; set; }
        public int? FkNguoilh { get; set; }
        public short? FkLoaitien { get; set; }
        public double? CTigia { get; set; }
        public short? FkPhongban { get; set; }
        public string FkTkno { get; set; }
        public string FkTkco { get; set; }
        public decimal? CPsno { get; set; }
        public decimal? CPsco { get; set; }
        public string CDiengiai { get; set; }
        public string CDgdong { get; set; }
        public short? FkThutruong { get; set; }
        public short? FkThuquy { get; set; }
        public short? FkKetoan { get; set; }
        public short? FkKttruong { get; set; }
        public short? FkNguoilap { get; set; }
        public short? FkThukho { get; set; }
        public short? FkKhoxuat { get; set; }
        public short? FkKhonhap { get; set; }
        public short? FkKexuat { get; set; }
        public short? FkKenhap { get; set; }
        public short? FkNguoigiao { get; set; }
        public short? FkVthh { get; set; }
        public short? FkDvt { get; set; }
        public double? CSoluong { get; set; }
        public decimal? CDongia { get; set; }
        public float? CVat { get; set; }
        public short? FkVuviec { get; set; }
        public short? FkPttt { get; set; }
        public short? CHantt { get; set; }
        public DateTime? CHantt2 { get; set; }
        public byte CLoaibt { get; set; }
        public bool? CCopy { get; set; }
        public bool? CPosted { get; set; }
        public short? CPoster { get; set; }
        public short? FkUser { get; set; }
        public DateTime? CDatetime { get; set; }
        public string CSoxe { get; set; }
        public decimal? CKm { get; set; }
        public bool? CPromo { get; set; }
        public int FkOrder { get; set; }
        public bool? CTrong { get; set; }
        public byte CLoaixn { get; set; }
        public byte CLoaict { get; set; }
        public short? FkKmp { get; set; }
        public short? FkDtcp { get; set; }
        public short? FkPhanxuong { get; set; }
        public int? CHoadon { get; set; }
        public int? FkLsx { get; set; }
        public int? FkLsxct { get; set; }
        public bool? CCpsx { get; set; }
        public string CMst { get; set; }
        public string CKhthue { get; set; }
        public byte? CChatluong { get; set; }
        public byte? CMrb { get; set; }
        public decimal? CSlkiemtra { get; set; }
        public short? FkLdhh { get; set; }
        public int? FkKhachhangco { get; set; }
        public int? FkTscd { get; set; }
        public string CSophieutralai { get; set; }
        public string CNote { get; set; }
        public int? FkNvkd { get; set; }
        public short? FkKmpc { get; set; }
        public bool? CKhuno { get; set; }
        public bool? CKhuco { get; set; }
        public decimal? CTienthue { get; set; }
        public string CSohdgtgt { get; set; }
        public string CNguoilh { get; set; }
        public short? FkModifyuser { get; set; }
        public string CThanhtoan { get; set; }
        public short? FkLdtg { get; set; }
        public short? FkNguonvon { get; set; }
        public bool? CLaphd { get; set; }
        public decimal? CTheobo { get; set; }
        public string CMathang { get; set; }
        public byte? FkLoaidl { get; set; }
        public decimal? CChietkhau { get; set; }
        public int? FkDondathang { get; set; }
        public decimal? CSlthung { get; set; }
        public int? FkQuicach { get; set; }
        public decimal? CTienhang { get; set; }
        public bool? CCpbanhang { get; set; }
        public decimal? CPsno2 { get; set; }
        public decimal? CPsco2 { get; set; }
        public string CDiengiai2 { get; set; }
        public short? FkCuocvanchuyen { get; set; }
        public short? FkSoxe { get; set; }
        public decimal? CDongiatc { get; set; }
        public short? FkChucnang { get; set; }
        public short? FkCa { get; set; }
        public short? FkTotruong { get; set; }
        public string CKhdiachi { get; set; }
        public decimal? CTienthue2 { get; set; }
        public short? FkSochuyen { get; set; }
        public int? FkHangvanchuyen { get; set; }
        public string CNguoivanchuyen { get; set; }
        public string CField1 { get; set; }
        public string CField2 { get; set; }
        public bool? CExtraentry { get; set; }
        public string CMauso { get; set; }
        public string CTk { get; set; }
        public int? FkTour { get; set; }
        public short? CStt { get; set; }
        public decimal? CSoluongxuat { get; set; }
        public string CTmpdichdanh { get; set; }
        public byte? FkThutruong02 { get; set; }
        public byte? FkKttruong02 { get; set; }
        public byte? FkKetoan02 { get; set; }
        public byte? FkThuquy02 { get; set; }
        public byte? FkNguoilap02 { get; set; }
        public byte? FkThukho02 { get; set; }
        public byte? FkNguoigiao02 { get; set; }
        public bool? CButtoanthem { get; set; }
        public string CSophieucu { get; set; }
        public decimal? CFob { get; set; }
        public decimal? CF { get; set; }
        public decimal? CI { get; set; }
        public decimal? CCif { get; set; }
        public decimal? CCif2 { get; set; }
        public decimal? CThuenk { get; set; }
        public decimal? CGttruocthue { get; set; }
        public decimal? CGttruocthue2 { get; set; }
        public short? FkCostCenter { get; set; }
        public bool? CImportData { get; set; }
        public decimal? CTienhangvanchuyen { get; set; }
        public string CSotknh { get; set; }
        public int? FkVoyage { get; set; }
        public string CBillOflading { get; set; }
        public string CVoyage { get; set; }
        public string CVessel { get; set; }
        public DateTime? CEta { get; set; }
        public string CPol { get; set; }
        public string CPod { get; set; }
        public string CPoreceive { get; set; }
        public string CPodelivery { get; set; }
        public int? FkBillOflading { get; set; }
        public byte? CDain { get; set; }
        public DateTime? CLastexport { get; set; }
        public int? FkVthhLuu { get; set; }
        public int? FkNhomKc { get; set; }
        public string CBookingnote { get; set; }
        public int? FkBookingnote { get; set; }
        public int? FkDtcpLuu { get; set; }
        public bool? CImportXuat { get; set; }
        public decimal? CCkTienmat { get; set; }
        public int? FkQlxDenghixuat { get; set; }
        public int? FkDtcpco { get; set; }
        public byte? CUpdate { get; set; }
        public string CKyhieumau { get; set; }
        public string CMahoadon { get; set; }
        public decimal? CNguyengia { get; set; }
        public int? FkVitri { get; set; }
        public string CSolo { get; set; }
        public DateTime? CHansudung { get; set; }
        public bool? CHetSl { get; set; }
    }
}
